version: '3.3'

# Cloudflare DNS Token = SkWxzNwo9vpDxZRPuDL26w05fFkmBMCrGVw042n

networks:
  default:
    driver: bridge
  npm_proxy:
    driver: bridge
    name: npm_proxy

services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://password.terrhyland.com"
    volumes:
      - ~/docker/config/vaultwarden:/data
    networks:
      - npm_proxy

  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    container_name: nginx-proxy-manager
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ~/docker/config/npm/config:/config
      - ~/docker/config/npm/letsencrypt:/etc/letsencrypt
      - ~/docker/config/npm/data:/data
    environment:
#      - DB_SQLITE_FILE=/config/database.sqlite
#      - DISABLE_IPV6=true
      - PUID=3000
      - PGID=3000
    networks:
      - npm_proxy
    security_opt:
      - no-new-privileges=true

  overseerr:
    image: sctx/overseerr:latest
    restart: unless-stopped
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      - PUID=3000
      - PGID=3000
    ports:
      - 5055:5055
    volumes:
      - ~/docker/config/overseer:/app/config
    networks:
      - npm_proxy

  gluetun:
    image: qmcgaw/gluetun
    restart: unless-stopped
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
#      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/docker/config/gluetun:/config
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=p9227729
      - OPENVPN_PASSWORD=sagyQxDt8i
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=America/New_York

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - ~/docker/config/qbittorrent:/config
      - /mnt/prox-share/data/torrents:/data/torrents
#    ports:
#      - 8085:8085
#      - 6881:6881
#      - 6881:6881/udp
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - ~/docker/config/radarr:/config
      - /mnt/prox-share/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - npm_proxy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - ~/docker/config/sonarr:/config
      - /mnt/prox-share/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - npm_proxy

  sonarr2:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr2
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - ~/docker/config/sonarr2:/config
      - /mnt/prox-share/data:/data
    ports:
      - 8988:8989
    networks:
      - npm_proxy
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/docker/config/portainer:/data
    environment:
      - TZ=America/New_York
    ports:
      - 9000:9000
    networks:
      - npm_proxy
    

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - ~/docker/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - npm_proxy

  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    ports:
      - 1935:1935 # RMTP
      - 8554:8554 # RSTP
      - 8888:8888 # HLS
      - 5000:5000 # Web-UI
    environment:
      - WYZE_EMAIL=$WYZE_EMAIL
      - WYZE_PASSWORD=$WYZE_PASSWORD
      - ENABLE_AUDIO=True
      - API_ID=4e4a9de7-ebe4-4d24-8236-e7f1038db57c
      - API_KEY=$WYZE_API_KEY
    networks:
      - npm_proxy

  spotify-poppin:
    container_name: spotify-poppin
    restart: unless-stopped
    build: ~/docker/Spotify-Poppin/
    networks:
      - npm_proxy
    ports:
      - 8889:8889